# Generated by Django 6.0.7 on 2026-07-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_user_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_or_birth',
            new_name='date_of_birth',
        ),
    ]
