# Generated by Django 6.0.7 on 2026-08-05 17:01

import django_resized.forms
import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[200, 200], upload_to=social.models.get_upload_image, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
