# Generated by Django 6.0.7 on 2026-08-14 16:33

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_post_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=social.models.get_upload_path, verbose_name='تصویر'),
        ),
    ]
