# Generated by Django 6.0.7 on 2026-08-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_useraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraction',
            options={'verbose_name': 'اکشن', 'verbose_name_plural': 'اکشن ها'},
        ),
    ]
