# Generated by Django 6.0.7 on 2026-08-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_useraction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike'), ('follow', 'follow'), ('unfollow', 'unfollow'), ('save', 'save'), ('unsave', 'unsave'), ('comment', 'comment'), ('view', 'view'), ('share', 'share')], max_length=20),
        ),
    ]
