# Generated by Django 6.0.7 on 2026-08-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_alter_useraction_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('subject', models.CharField(choices=[('پیشنهاد', 'پیشنهاد'), ('انتقاد', 'انتقاد'), ('گزارش', 'گزارش')], max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تیکت ',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
    ]
